name: super_strapi
description: A Strapi dev library for Dart developers for dart class generation from strapi models and doing graph queries.
version: 0.9.0-alpha+3
homepage: https://github.com/ondbyte/super_strapi
environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies:
#  path: ^1.7.0
  args: ^2.0.0
  path: ^1.7.0
  code_builder: ^3.7.0
  dart_style: any
  inflection2: ^0.4.3
  yaml: ^3.1.0





dev_dependencies:
  pedantic: ^1.9.0
